[package]
name = "types__scopes"
version = "0.1.0"
edition = "2018"

[features]
default = []
flatbuf = ["differential_datalog/flatbuf","ddlog_rt/flatbuf", "ddlog_std/flatbuf", "ddlog_bigint/flatbuf", "ddlog_log/flatbuf", "debug/flatbuf", "internment/flatbuf", "types__ast/flatbuf", "types__vec/flatbuf", "types__utils/flatbuf", "types__group/flatbuf", "types__inputs/flatbuf", "types__config/flatbuf", "types__regex/flatbuf"]
c_api = ["differential_datalog/c_api","ddlog_rt/c_api", "ddlog_std/c_api", "ddlog_bigint/c_api", "ddlog_log/c_api", "debug/c_api", "internment/c_api", "types__ast/c_api", "types__vec/c_api", "types__utils/c_api", "types__group/c_api", "types__inputs/c_api", "types__config/c_api", "types__regex/c_api"]

[dependencies]
differential_datalog = { path = "../../differential_datalog" }
ddlog_derive = { path = "../../ddlog_derive" }
abomonation = "0.7"
ordered-float = { version = "2.0.0", features = ["serde"] }
fnv = "1.0.2"
once_cell = "1.4.1"
libc = "0.2"
time = { version = "0.2", features = ["serde"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
num = "0.3"
erased-serde = "0.3"
differential-dataflow = { git = "https://github.com/ddlog-dev/differential-dataflow", branch = "ddlog-2" }
timely = { git = "https://github.com/ddlog-dev/timely-dataflow", branch = "ddlog-2" }

ddlog_rt = { path = "../ddlog_rt" }
ddlog_std = { path = "../ddlog_std" }
ddlog_bigint = { path = "../ddlog_bigint" }
ddlog_log = { path = "../ddlog_log" }
debug = { path = "../debug" }
internment = { path = "../internment" }
types__ast = { path = "../ast" }
types__vec = { path = "../vec" }
types__utils = { path = "../utils" }
types__group = { path = "../group" }
types__inputs = { path = "../inputs" }
types__config = { path = "../config" }
types__regex = { path = "../regex" }

[lib]
name = "types__scopes"
path = "scopes.rs"